#!/bin/bash

crontab -l |grep -v "gmetric -n roxie_instances -v" > /tmp/.cronTabCopy
echo "* * * * * /usr/bin/gmetric -n roxie_instances -v `ps -ef | grep -i "roxie --topology" | grep -v grep -c` -u instances -t uint32 > /dev/null" >> /tmp/.cronTabCopy
crontab /tmp/.cronTabCopy



