#!/usr/bin/expect

spawn apt-get install ganglia-webfrontend gmetad ganglia-monitor python-lxml collectd-core ganglia-monitor python-lxml libltdl7 libganglia1 libapr1 libconfuse0 libxslt1.1 libconfuse-common -y
expect "<No>"
send  "\r"
expect "<No>"
send "\r"
spawn sh ./install_graphs_helper.sh >> install.log

